export type ChalkColorType =
    'black' |
    'red' |
    'green' |
    'yellow' |
    'blue' |
    'magenta' |
    'cyan' |
    'white' |
    'gray' |
    'grey' |
    'blackBright' |
    'redBright' |
    'greenBright' |
    'yellowBright' |
    'blueBright' |
    'magentaBright' |
    'cyanBright' |
    'whiteBright' |
    'bgBlack' |
    'bgRed' |
    'bgGreen' |
    'bgYellow' |
    'bgBlue' |
    'bgMagenta' |
    'bgCyan' |
    'bgWhite' |
    'bgBlackBright' |
    'bgRedBright' |
    'bgGreenBright' |
    'bgYellowBright' |
    'bgBlueBright' |
    'bgMagentaBright' |
    'bgCyanBright' |
    'bgWhiteBright';
